site_name: kOps - Kubernetes Operations
# strict: true
repo_name: 'kubernetes/kops'
repo_url: 'https://github.com/kubernetes/kops'
site_url: 'https://kops.sigs.k8s.io'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: ' ¶'
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: 'material/cloud-outline'
  favicon: 'img/logo-notext.svg'
  palette:
    primary: 'teal'
    accent: 'green'
plugins:
  - search
  - macros:
      module_name: hack/mkdocs_macros/feature_stability_table
extra_css: [extra.css]

nav:
  - Welcome:
    - Welcome: "index.md"
    - Releases & Versioning: "welcome/releases.md"
    - Office Hours: "welcome/office_hours.md"
    - Values: "values.md"
  - Getting Started:
    - Installing: "getting_started/install.md"
    - Deploying to AWS: "getting_started/aws.md"
    - Deploying to GCE - Alpha: "getting_started/gce.md"
    - Deploying to OpenStack - Beta: "getting_started/openstack.md"
    - Deploying to Digital Ocean - Beta: "getting_started/digitalocean.md"
    - Deploying to Spot Ocean - Alpha: "getting_started/spot-ocean.md"
    - Deploying to Azure - Alpha: "getting_started/azure.md"
    - kOps Commands: "getting_started/commands.md"
    - kOps Arguments: "getting_started/arguments.md"
    - kubectl usage: "getting_started/kubectl.md"
    - Production setup: "getting_started/production.md"
  - CLI:
    - kops: "cli/kops.md"
    - kops completion: "cli/kops_completion.md"
    - kops create: "cli/kops_create.md"
    - kops delete: "cli/kops_delete.md"
    - kops distrust: "cli/kops_distrust.md"
    - kops edit: "cli/kops_edit.md"
    - kops export: "cli/kops_export.md"
    - kops get: "cli/kops_get.md"
    - kops promote: "cli/kops_promote.md"
    - kops replace: "cli/kops_replace.md"
    - kops rolling-update: "cli/kops_rolling-update.md"
    - kops toolbox: "cli/kops_toolbox.md"
    - kops trust: "cli/kops_trust.md"
    - kops update: "cli/kops_update.md"
    - kops upgrade: "cli/kops_upgrade.md"
    - kops validate: "cli/kops_validate.md"
    - kops version: "cli/kops_version.md"
  - API:
    - Cluster Resource: "cluster_spec.md"
    - InstanceGroup Resource: "instance_groups.md"
  - Addons:
    - Addons: "addons.md"
  - Operations:
    - Updates & Upgrades: "operations/updates_and_upgrades.md"
    - Rolling Updates: "operations/rolling-update.md"
    - Working with Instance Groups: "tutorial/working-with-instancegroups.md"
    - Using Manifests and Customizing: "manifests_and_customizing_via_api.md"
    - High Availability: "operations/high_availability.md"
    - Scaling: "operations/scaling.md"
    - Karpenter: "operations/karpenter.md"
    - Local asset repositories: "operations/asset-repository.md"
    - Instancegroup images: "operations/images.md"
    - Cluster configuration management: "changing_configuration.md"
    - Cluster Templating: "operations/cluster_template.md"
    - GPU setup: "gpu.md"
    - Label management: "labels.md"
    - Rotate Secrets: "operations/rotate-secrets.md"
    - Service Account Token Volume: "operations/service_account_token_volumes.md"
    - Moving from a Single Master to Multiple HA Masters: "single-to-multi-master.md"
    - Running kOps in a CI environment: "continuous_integration.md"
    - Gossip DNS: "gossip.md"
    - etcd:
      - etcd administration: "operations/etcd_administration.md"
      - etcd backup, restore and encryption: "operations/etcd_backup_restore_encryption.md"
      - Moving from a Single Master to Multiple HA Masters: "single-to-multi-master.md"
      - etcd3 Migration: "etcd3-migration.md"
    - Troubleshooting: "operations/troubleshoot.md"

  - Networking:
    - Networking Overview: "networking.md"
    - CNI:
      - AWS VPC: "networking/aws-vpc.md"
      - Calico: "networking/calico.md"
      - Canal: "networking/canal.md"
      - Cilium: "networking/cilium.md"
      - Flannel: "networking/flannel.md"
      - Kube-Router: "networking/kube-router.md"
      - Weave: "networking/weave.md"
    - IPv6: "networking/ipv6.md"
    - Run kOps in an existing VPC: "run_in_existing_vpc.md"
    - Supported network topologies: "topology.md"
    - Subdomain setup: "creating_subdomain.md"
  - Security:
    - Security: "security.md"
    - Advisories: "advisories/README.md"
    - Bastion setup: "bastion.md"
    - Instance IAM roles: "iam_roles.md"
    - MFA setup: "mfa.md"
    - Security Groups: "security_groups.md"
  - Advanced:
    - Download Config: "advanced/download_config.md"
    - Subdomain NS Records: "advanced/ns.md"
    - Experimental: "advanced/experimental.md"
    - Cluster boot sequence: "boot-sequence.md"
    - Philosophy: "philosophy.md"
    - State store: "state.md"
    - AWS China: "aws-china.md"
    - Custom CA: "custom_ca.md"
    - Horizontal Pod Autoscaling: "horizontal_pod_autoscaling.md"
    - Egress Proxy: "http_proxy.md"
    - Node Resource Allocation: "node_resource_handling.md"
    - Terraform: "terraform.md"
    - Authentication: "authentication.md"
  - Contributing:
    - Getting Involved and Contributing: "contributing/index.md"
    - New Kubernetes Version: "contributing/new_kubernetes_version.md"
    - Our Release Process: "contributing/release-process.md"
    - Releasing With Homebrew: "contributing/homebrew.md"
    - Updating The Default Base AMI: "contributing/update_ami_versions.md"
    - Building: "contributing/building.md"
    - Adding a feature: "contributing/adding_a_feature.md"
    - Testing: "contributing/testing.md"
    - Testing preview versions: "contributing/test_versions.md"
    - Developing using Docker: "contributing/Docker.md"
    - Documentation Guidelines: "contributing/documentation.md"
    - Hack Directory: "contributing/hack.md"
    - How to update kOps API: "contributing/api_updates.md"
    - Low level description on how kOps works: "contributing/how_it_works.md"
    - Notes on Gossip design: "contributing/gossip.md"
    - Notes on master instance sizing: "contributing/instancesizes.md"
    - Vendoring: "contributing/vendoring.md"
    - Ports: "contributing/ports.md"
    - Cluster Addons & Manager : "contributing/addons.md"
  - Releases:
    - "1.23": releases/1.23-NOTES.md
    - "1.22": releases/1.22-NOTES.md
    - "1.21": releases/1.21-NOTES.md
    - "1.20": releases/1.20-NOTES.md
    - "1.19": releases/1.19-NOTES.md
    - "1.18": releases/1.18-NOTES.md
    - "1.17": releases/1.17-NOTES.md
    - "1.16": releases/1.16-NOTES.md
    - "1.15": releases/1.15-NOTES.md
    - "1.14": releases/1.14-NOTES.md
    - "1.13": releases/1.13-NOTES.md
    - "1.12": releases/1.12-NOTES.md
    - "1.11": releases/1.11-NOTES.md
    - "1.10": releases/1.10-NOTES.md
    - "1.9": releases/1.9-NOTES.md
    - "1.8": releases/1.8-NOTES.md
    - "1.7": releases/1.7-NOTES.md
    - "1.6": releases/1.6-NOTES.md
    - "1.4": releases/1.4-NOTES.md
